# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  python: circleci/python@2.1.1


jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements-test.txt
          pkg-manager: pip
      - run:
          name: execute tests
          command: python -m coverage run -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  dist:
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: build dist
          command: python setup.py sdist bdist_wheel

workflows:
  test_app:
    jobs:
      - build
      - dist:
          requires:
            - build # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: master # only deploy when on main
